# Plugin Created By JAhimaz | ItsJustDsAW

############################################################
# +------------------------------------------------------+ #
# |                     = EZLOTTERY =                    | #
# +------------------------------------------------------+ #
############################################################

# Enable the Lottery Plugin
plugin-enabled: true

#Maximum Amount of Tickets per player
max-tickets: 10
price-per-ticket: 10000.00

#Will take a portion of the winnings and store it in a player economy account
enable-tax: true
#Amount in % to tax
tax-amount: 20
#Must be a player in the server (Registered atleast once)
tax-account: "ServerBank"

#How long will each lottery run before it draws a winner
lottery-timer: 600

#Delay before the next Lottery
lottery-delay: 42600

# DONT TOUCH THE BELOW, IT WILL MESS UP THE PLUGIN, THANKS! #
current-lottery-number: 0
plugin-version: 1.0.0
# DONT TOUCH THE ABOVE, IT WILL MESS UP THE PLUGIN, THANKS! #