# Plugin Created By JAhimaz | ItsJustDsAW

############################################################
# +------------------------------------------------------+ #
# |                     = EZLOTTERY =                    | #
# |                     VERSION 1.0.0                    | #
# +------------------------------------------------------+ #
############################################################

max-tickets:

price-per-ticket: 2000
