# Plugin Created By JAhimaz | ItsJustDsAW

############################################################
# +------------------------------------------------------+ #
# |                     = EZLOTTERY =                    | #
# +------------------------------------------------------+ #
############################################################

# Enable the Lottery Plugin
plugin-enabled: true

#Maximum Amount of Tickets per player
max-tickets: 10
price-per-ticket: 10000.00

#Will take a portion of the winnings and store it in a player economy account
enable-tax: false
#Amount in % to tax
tax-amount: 20
#Must be a player in the server (Registered atleast once)
tax-account: "ServerBank"

# ================ All values are represented in Seconds ==========================
#Initial Lottery (When you startup the server, how long before the first Lottery)
first-lottery-timer: 30
#How long will each lottery run before it draws a winner
lottery-timer: 600
#Delay before the next Lottery
lottery-delay: 21000

# Open Source - Credit Must Be Mentioned