name: EzLottery
version: 1.3
main: com.jahimaz.EzLottery
api-version: 1.13
load: STARTUP
authors: [ItsJustDsAW]
depend: [Vault]
softdepend: [PlaceholderAPI]
description: A simple, fast and easy lottery plugin with placeholder API support
commands:
  lottery:
    description: Launch the lottery
    aliases: [lm, lot, pot]
permissions:
  lottery.reload:
    description: Reloads the lottery Plugin.
  lottery.start:
    description: Manually Start a lottery.
  lottery.cancel:
    description: Manually cancel a lottery.